### ISSUE TITLE
CONTROLLER: MISSING link between the GUI and the LOGIC part for a BOARD

### ISSUE THREAD

**Issue by jucom** [nmaguirre/eiffel-sudoku#36]
When you modify a cell on the board only the board from the GUI change. 
It would be nice if both boards where connected. Without that we cannot use, for example, the  initialization of SUDOKU_BOARD in the MAIN_WINDOW

**Comment by cesarcorne** [comment]
I did that make_with_random_values recive a parameter of dificult, so when someone finish the issue "selection of levels" so you pay attention with the parameter.

**Comment by FRaverta** [comment]
I try link controller with logic and gui. I put a feature in MAIN_WINDOW called controller(type: SUDOKU_CONTROLLER), it is the same object that APLICACION.controller because SUDOKU_CONTROLLER is a SINGLETON. Also, for link GUI whit controller I create a controller in method prepare(APLICACION) and set GUI to controller and controller to MAIN_WINDOWS, in this method. 
I choose this option, I don't know if it's a good practice of design, but I believe that runs correctly.
