### ISSUE TITLE
Optimization: repeated_element_in_col and repeated_element_in_row

### ISSUE THREAD

**Issue by mdonatti** [nmaguirre/eiffel-sudoku#71]

**Comment by mdonatti** [comment]
fc0d5d6

**Comment by gamab** [comment]
When you check a row or a column you need to check it from the beginning to the end, not only the cells after, don't you think?

**Comment by mdonatti** [comment]
yes, with i check from the start.. obvious only repeated cases

**Comment by e-marchisio** [comment]
The idea of the implementations was to avoid doing that. 
It has no sense to control the previous numbers too of the current number, because if there was an
error, it had been notified before.

Here's an example:     1 6 2 8 3 5 5
To the first ocurrence of 5, doesn't matter the previous numbers, only the following ones.

It would be different if the implementations of the features would take both column and row as parameters.

**Comment by gamab** [comment]
Yes and that's what is done isn't it?

My comment was there just because I thought that when a cell is set we were verifying for this cell if it is conflicts with another cell of the board. But what we actually do is checking the entire board each time we insert a cell, so yes checking previous cells doesn't matter when checking the whole board.

**Comment by e-marchisio** [comment]
Yes.

With this idea, to check that property before an "insert" with the cell (2,3) for example, it should be enough to call: repeated_element_in_col(3) or repeated_element_in_row(2) to know if there is a repeated element in the column or row of the cell.
