### ISSUE TITLE
red paint the cell with wrong value

### ISSUE THREAD

**Issue by diegogastaldi** [nmaguirre/eiffel-sudoku#82]
sorry, I thought you had assigned and uploaded, but I see no want him out

**Comment by gamab** [comment]
I will do a function Insertion_Correct(row,col : integer) : Boolean in Sudoku_Board.

**Comment by federf** [comment]
when a new random game is created the values charged by SUDOKU_BOARD/make_whit _random_values are colored in red instead and stay so. BUGGGG to be solved.

**Comment by cesarcorne** [comment]
Also if you insert a number, the number will be painted

**Comment by gamab** [comment]
#90

**Comment by gamab** [comment]
If you insert a 2 in a square in which there is already a 2 this new 2 will be painted in red. If you delete the older 2, normally the newest 2 should be painted back to the default color. This is not what is happening.
See photo if this isn't a clear explanation...
![insert_wrong1](https://f.cloud.github.com/assets/5232696/1111692/509c49f0-19b7-11e3-85f5-1396ff171561.png)

I found a solution which could solve this problem. In sudoku_controller, we keep a list of each cell that has been inserted with conflict = a list of red cells. After each insertion/deletion we can check this list to see if we settled one (or more) conflict(s) and paint back one (or more) cell(s) into the default color.

This list has to be in Sudoku_Controller, because it's aim is clearly to control.

Do you think I should open another issue and do it ? Or is it part of this issue ? Is anyone assigned to this issue ?

**Comment by nmaguirre** [comment]
I think it's part of this issue.

**Comment by gamab** [comment]
Ok I have done it in f543802

**Comment by gamab** [comment]
I didn't think that it was possible to insert twice the same red cell in the list, but it is, I have to solve this problem. 
Also I forgot to commit class COORDS.

**Comment by gamab** [comment]
Changes made in e114942.
