### ISSUE TITLE
Wrong commit DO NOT PULL

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#98]
I commit eiffel_sudoku.ecf, thinking I had to since I had a cluster. But if you pull conf file won't work. Hence DO NOT PULL.
I am searching how to uncommit

**Comment by nmaguirre** [comment]
I'm fixing the .ecf. I'll commit it in a minute.

**Comment by nmaguirre** [comment]
Solved in rev. d4e950b.

**Comment by gamab** [comment]
Thanks a lot, I was afraid I broke everything.
Why, when I had a cluster with new classes, they don't show up like they should in others computer after a pull?

**Comment by nmaguirre** [comment]
The problem is that the new cluster's folder is written as a absolute path (e.g., c:\Documents and Settings\SuperCoolUser\My Projects...\eiffel_sudoku\solver) instead of the path being relative (e.g., .\solver). That, together with library information (e.g., which are precompiled and which not) might cause compilation or configuration issues.
